name: Test

on:
  workflow_dispatch:

jobs:
  test:
    name: Test ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        #python-version: [3.7, 3.8, 3.9, 3.10.0-rc.2]
        python-version: [3.9]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

#      - name: Install CUDA toolkit
#        uses: Jimver/cuda-toolkit@v0.2.4
#        id: cuda-toolkit
#        with:
#          cuda: '11.2.2'

#      - name: Check CUDA
#        run: |
#          echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
#          echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
#          nvcc -V

      - name: Install numba-rtx
        run: |
          python -m pip install -ve .[tests]
          python -m pip list

      - name: Run tests
        run: |
          python -m pytest -v rtx/tests
